pipeline {
    agent any

    stages {

        stage('Clone Repo') {
            steps {
                git 'https://github.com/vanshchoudhary108/devops-cicd-project.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                sh 'docker build -t devops-site -f docker/Dockerfile .'
            }
        }

        stage('Run Container') {
            steps {
                sh 'docker run -d -p 8082:80 devops-site'
            }
        }

    }
}
